# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastGLSCPP <- function(X, y, sigma, size_param = NULL, ncores = 1L) {
    .Call(`_genStatPipeline_fastGLSCPP`, X, y, sigma, size_param, ncores)
}

fastGLSIBDCPP <- function(mp, y, sigma, ref, size_param = NULL, ncores = 1L) {
    .Call(`_genStatPipeline_fastGLSIBDCPP`, mp, y, sigma, ref, size_param, ncores)
}

LLQuadFormDiagCPP <- function(Y, vInv, size_param = NULL) {
    .Call(`_genStatPipeline_LLQuadFormDiagCPP`, Y, vInv, size_param)
}

